import type { GeometryConfig } from './config';
import { createRng, rngRange, smoothNoise1d } from './random';
import { hermiteXofY, type Pt, type XWaypoint } from './spline';

/**
 * The braid (§5.4) — the non-negotiable fix for the known failure mode.
 *
 * After the meeting BOTH thread paths are generated by phase-opposed
 * oscillations around the shared center axis:
 *
 *   her(y) = center(y) − A(y) · sin(φ(y))
 *   him(y) = center(y) + A(y) · sin(φ(y))
 *
 * (sign chosen so HER stays on her own left side immediately after the kiss;
 * the phase opposition is what guarantees genuine crossings at every zero of
 * sin). A(y) starts at 0 exactly at the meeting — a true tangent kiss with
 * no kink on either side — blooms to braidAmpStart by the first extreme,
 * then eases down to braidAmpEnd: the braid tightens as their life deepens.
 *
 * The organic pass (see DECISIONS.md) breaks the machine-regularity three
 * ways, all seeded and all crossing-safe:
 *  - the center axis itself wanders a little (shared by both threads, so
 *    crossings and phase opposition are untouched), pinned to the true
 *    center at the kiss and at the knot entry;
 *  - the shared amplitude carries ±6% smooth noise, so loops breathe;
 *  - crossings are jittered ±13px off the uniform grid and φ is a smooth
 *    Hermite through them, so no two loops are quite the same height while
 *    every shared milestone still lands exactly on a sine extreme.
 */

export interface BraidGeometry {
  her: Pt[];
  him: Pt[];
  /** y positions of the crossings, k = 1..n (φ = kπ), jittered */
  crossings: number[];
  /** noised amplitude at y — what the rendered threads actually use */
  amplitudeAt: (y: number) => number;
  /** un-noised amplitude envelope (monotone after the bloom; for tests) */
  baseAmplitudeAt: (y: number) => number;
  /** the wandering center axis (drift is 0 at kiss and knot entry) */
  centerAt: (y: number) => number;
}

const easeOutCubic = (t: number) => 1 - Math.pow(1 - t, 3);
const easeInOutCos = (t: number) => 0.5 - 0.5 * Math.cos(Math.PI * t);
const smoothstep = (t: number) => {
  const c = Math.max(0, Math.min(1, t));
  return c * c * (3 - 2 * c);
};

export function buildBraid(
  yMeet: number,
  yBraidEnd: number,
  cfg: GeometryConfig,
  step = 6,
): BraidGeometry {
  const scale = cfg.widthPx / 1000;
  const xc = cfg.widthPx / 2;
  const T = cfg.crossingSpacing;

  const aStart = cfg.braidAmpStart * scale;
  const aEnd = cfg.braidAmpEnd * scale;
  const yFirstExtreme = yMeet + 2.5 * T;

  const baseAmplitudeAt = (y: number): number => {
    if (y <= yMeet) return 0;
    if (y <= yFirstExtreme) {
      // bloom: 0 → aStart, fast start, smooth arrival
      return aStart * easeOutCubic((y - yMeet) / (yFirstExtreme - yMeet));
    }
    if (y >= yBraidEnd) return aEnd;
    // tighten: aStart → aEnd
    const t = (y - yFirstExtreme) / (yBraidEnd - yFirstExtreme);
    return aStart + (aEnd - aStart) * easeInOutCos(t);
  };

  // ±6% breathing on the loop widths, fading in after the kiss.
  const ampNoise = smoothNoise1d(cfg.seed ^ 0xa317, 700);
  const amplitudeAt = (y: number): number => {
    const grow = smoothstep((y - yMeet) / (yFirstExtreme - yMeet));
    return baseAmplitudeAt(y) * (1 + 0.06 * ampNoise(y - yMeet) * grow);
  };

  // The whole weave sways gently, like handwork — shared by both threads
  // so every crossing stays a crossing. Pinned to 0 at kiss and knot entry.
  const driftNoise = smoothNoise1d(cfg.seed ^ 0xd21f7, 1100);
  const driftAmp = 12 * scale;
  const centerAt = (y: number): number => {
    const env =
      smoothstep((y - yMeet) / 350) *
      smoothstep((yBraidEnd - y) / 350);
    return xc + driftAmp * driftNoise(y - yMeet) * env;
  };

  // ── eased, jittered phase ──
  // Waypoints: the kiss (φ=0), every crossing (φ=kπ, jittered ±13px so
  // spacing stays within the tested 180–260px window), every milestone
  // extreme (fixed — shared milestones must sit exactly on extremes), and
  // the knot entry.
  const halfTurns = Math.round(((yBraidEnd - yMeet) / T) * 2) / 2;
  const crossCount = Math.floor(halfTurns);
  const rng = createRng(cfg.seed ^ 0xc405);
  const crossings: number[] = [];
  for (let k = 1; k <= crossCount; k++) {
    crossings.push(yMeet + k * T + rngRange(rng, -13, 13));
  }

  const phiWay: XWaypoint[] = [{ y: yMeet, x: 0 }];
  for (let k = 1; k <= crossCount; k++) {
    phiWay.push({ y: crossings[k - 1], x: k * Math.PI });
  }
  // milestone extremes: 2.5π, 4.5π, … (see layout.ts); the first extreme
  // and the braid end are constrained even without a milestone there
  for (let m = 2.5; m < halfTurns; m += 2) {
    phiWay.push({ y: yMeet + m * T, x: m * Math.PI });
  }
  phiWay.push({ y: yBraidEnd, x: halfTurns * Math.PI });
  phiWay.sort((a, b) => a.y - b.y);
  const phaseAt = hermiteXofY(phiWay);

  const her: Pt[] = [];
  const him: Pt[] = [];
  const n = Math.ceil((yBraidEnd - yMeet) / step);
  for (let i = 0; i <= n; i++) {
    const y = i === n ? yBraidEnd : yMeet + i * step;
    const off = amplitudeAt(y) * Math.sin(phaseAt(y));
    const c = centerAt(y);
    her.push({ x: c - off, y });
    him.push({ x: c + off, y });
  }

  return { her, him, crossings, amplitudeAt, baseAmplitudeAt, centerAt };
}

/**
 * Over/under assignment at braid crossing k (1-based, §5.4):
 * HER passes over when k is even, HIS when k is odd.
 */
export function overThreadAtCrossing(k: number): 'her' | 'him' {
  return k % 2 === 0 ? 'her' : 'him';
}
