import type { GeometryConfig } from './config';
import type { Pt } from './spline';

/**
 * The braid (§5.4) — the non-negotiable fix for the known failure mode.
 *
 * After the meeting BOTH thread paths are generated by phase-opposed
 * oscillations around the shared center axis:
 *
 *   her(y) = xc − A(y) · sin(φ(y))
 *   him(y) = xc + A(y) · sin(φ(y))
 *
 * (sign chosen so HER stays on her own left side immediately after the kiss;
 * the phase opposition is what guarantees genuine crossings at every zero of
 * sin). φ advances linearly: one crossing every cfg.crossingSpacing px.
 *
 * A(y) starts at 0 exactly at the meeting — this is what makes the meeting a
 * true tangent kiss (both threads touch the axis with zero slope, no kink) —
 * blooms to braidAmpStart by the first extreme, then eases down to
 * braidAmpEnd at the braid's end: the braid visibly tightens as their life
 * together deepens.
 */

export interface BraidGeometry {
  her: Pt[];
  him: Pt[];
  /** y positions of the crossings, k = 1..n (φ = kπ) */
  crossings: number[];
  /** amplitude at a given y (exposed for marker sizing/tests) */
  amplitudeAt: (y: number) => number;
}

const easeOutCubic = (t: number) => 1 - Math.pow(1 - t, 3);
const easeInOutCos = (t: number) => 0.5 - 0.5 * Math.cos(Math.PI * t);

export function buildBraid(
  yMeet: number,
  yBraidEnd: number,
  cfg: GeometryConfig,
  step = 6,
): BraidGeometry {
  const scale = cfg.widthPx / 1000;
  const xc = cfg.widthPx / 2;
  const T = cfg.crossingSpacing;
  const aStart = cfg.braidAmpStart * scale;
  const aEnd = cfg.braidAmpEnd * scale;
  const yFirstExtreme = yMeet + 2.5 * T;

  const amplitudeAt = (y: number): number => {
    if (y <= yMeet) return 0;
    if (y <= yFirstExtreme) {
      // bloom: 0 → aStart, fast start, smooth arrival
      return aStart * easeOutCubic((y - yMeet) / (yFirstExtreme - yMeet));
    }
    if (y >= yBraidEnd) return aEnd;
    // tighten: aStart → aEnd
    const t = (y - yFirstExtreme) / (yBraidEnd - yFirstExtreme);
    return aStart + (aEnd - aStart) * easeInOutCos(t);
  };

  const phaseAt = (y: number): number => (Math.PI * (y - yMeet)) / T;

  const her: Pt[] = [];
  const him: Pt[] = [];
  const n = Math.ceil((yBraidEnd - yMeet) / step);
  for (let i = 0; i <= n; i++) {
    const y = i === n ? yBraidEnd : yMeet + i * step;
    const off = amplitudeAt(y) * Math.sin(phaseAt(y));
    her.push({ x: xc - off, y });
    him.push({ x: xc + off, y });
  }

  const halfTurns = Math.round((yBraidEnd - yMeet) / T * 2) / 2;
  const crossings: number[] = [];
  for (let k = 1; k <= Math.floor(halfTurns); k++) {
    crossings.push(yMeet + k * T);
  }

  return { her, him, crossings, amplitudeAt };
}

/**
 * Over/under assignment at braid crossing k (1-based, §5.4):
 * HER passes over when k is even, HIS when k is odd.
 */
export function overThreadAtCrossing(k: number): 'her' | 'him' {
  return k % 2 === 0 ? 'her' : 'him';
}
